### ISSUE TITLE
Leftover diagnostic println messages

### ISSUE THREAD

**Issue by pglamm** [razvn/jacoco-to-cobertura-gradle-plugin#17]
Thanks for the latest release allowing verbose or not. However, you left these in the code:

```kotlin
kotlinSources.forEach {
  println("Kotlin - ${it.canonicalPath}")
}
javaSources.forEach {
  println("Java - ${it.canonicalPath}")
}
```
I presume they were debug messages during testing. Happens to me sometimes too... :-)

**Comment by razvn** [comment]
Thanks for pointing out ;)
