### ISSUE TITLE
Hide `Cobertura report generated at [...]` message

### ISSUE THREAD

**Issue by remal** [razvn/jacoco-to-cobertura-gradle-plugin#25]
We prefer to keep our logs as simple as possible and output something only if it requires attention. Could you please hide `Cobertura report generated at [...]` log message? It's log level could be changed to `INFO` for example.

**Comment by razvn** [comment]
Sorry, I find useful to know when a plugin runs that it does something. 
If you don't want lifecycle messages in your build run gradle command with a different logging level than default: `-w` or `-q` (or set the right value in `gradle.properties`)
See: https://docs.gradle.org/current/userguide/logging.html#sec:choosing_a_log_level
