### ISSUE TITLE
add a config for manual setting the sources location

### ISSUE THREAD

**Issue by razvn** [razvn/jacoco-to-cobertura-gradle-plugin#8]
In case the sources detected are not well detected, setting a list of sources in the configuration of the plugin should add these dirs to the sources cobertura xml tag.

**Comment by tjerkw** [comment]
I just had a similar problem in a kotlin multiplatform project:

> 
> Task :shared:jacocoToCobertura FAILED
Conversion jacoco report to cobertura
Error while running JacocoToCobertura conversion: `SourceSet with name 'main' not found.
